/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prumahsakit;

import javax.swing.JOptionPane;
/**
 *
 * @author Owner
 */
public class cRegistrasiPasien extends javax.swing.JFrame {

    /**
     * Creates new form cRegistrasiPasien
     */
    
    public static String email;
    public static String nama;
    public static String nomor;
    public static String password;
    
    public cRegistrasiPasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1023, 768));
        getContentPane().setLayout(null);

        jTextField2.setBackground(new java.awt.Color(166, 191, 255));
        jTextField2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(610, 230, 340, 30);

        jTextField3.setBackground(new java.awt.Color(166, 191, 255));
        jTextField3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(610, 300, 340, 30);

        jTextField1.setBackground(new java.awt.Color(166, 191, 255));
        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(610, 370, 340, 30);

        jPasswordField1.setBackground(new java.awt.Color(166, 191, 255));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(610, 450, 340, 30);

        jPasswordField2.setBackground(new java.awt.Color(166, 191, 255));
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(610, 530, 340, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 580, 280, 60);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 110, 310, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pBackground/invisible.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(960, 450, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pBackground/eye.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(960, 450, 30, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pBackground/invisible.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(960, 530, 30, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pBackground/eye.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(960, 530, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pBackground/Purple and Pink Flat Color Login Page Simple Tablet UI Prototype (3).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       if(jPasswordField2.getText().equals(jPasswordField1.getText())){
            email = jTextField2.getText();
            nama = jTextField3.getText();
            nomor = jTextField1.getText();
            password = jPasswordField1.getText();
            
            JOptionPane.showMessageDialog(null, "REGISTRASI BERHASIL");
            JOptionPane.showMessageDialog(null, "Silahkan join untuk menggunakan aplikasi");
            
            dispose();
                cLogin lg = new cLogin();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(cRegistrasiPasien.EXIT_ON_CLOSE);
        }
        else{
            jLabel3.setText("Register Gagal, Harap Coba Lagi!!!");
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        jLabel10.setVisible(true);
        jLabel9.setVisible(false);
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        jLabel9.setVisible(true);
        jLabel10.setVisible(false);
        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cRegistrasiPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cRegistrasiPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cRegistrasiPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cRegistrasiPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cRegistrasiPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
